### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by frezbo**
Bump deps.

### CODE REVIEW

**Review by smira — COMMENTED** [review]
do we need to bump Talos version in the tests?

**Comment by frezbo** [comment]
> do we need to bump Talos version in the tests?

it uses the version in machinery

**Comment by smira** [comment]
I mean 1.5.0 is not available yet :)

**Review by smira — APPROVED** [review]

**Comment by frezbo** [comment]
> I mean 1.5.0 is not available yet :)

ahh yes, the test would fail :joy:

**Pull request merged**
