### PR TITLE
feat: use new tf sdk

### PR DESCRIPTION
**Pull request by frezbo**
Use new tf sdk and support dynamic values.

### CODE REVIEW

**Comment by frezbo** [comment]
This is trying to potentially fix all these:

Fixes: #11 - patches are now a native tf dynamic block
Fixes: #36 there's now a dedicated client_config block
Fixes: #37 endpoint is now optional and if not set defaults to the node
Fixes: #38 - both are now data sources
Fixes: #39 there's now a dedicated client_config block
Fixes: #41 - except machine secrets (since it needs to be once), both machine_config and cluster_kubeconfig are data sources
Fixes: #42 - tries to bail earlier for some common errors 
Fixes: #52 - tries to bail earlier for some common errors 
Fixes: #63 - tries to bail earlier for some common errors

**Review by smira — APPROVED** [review]
it would be awesome to have some tests!

**Pull request merged**
